from typing import Protocol, runtime_checkable, Optional, Dict, Any
from core.config.models import AppConfig, BotConfig

@runtime_checkable
class IConfigRepository(Protocol):
    """Protocol for loading, saving, and accessing application configuration."""
    config_path: str
    app_config: AppConfig

    def load(self) -> AppConfig: ...
    def save(self, raw_data: Optional[Dict[str, Any]] = None) -> bool: ...
    async def save_async(self, raw_data: Optional[Dict[str, Any]] = None) -> bool: ...
    def get_bot(self, bot_id: str) -> Optional[BotConfig]: ...

    @property
    def raw(self) -> Dict[str, Any]: ...

@runtime_checkable
class IStateRepository(Protocol):
    """Protocol for managing persistent runtime state."""
    state_path: str

    def load(self) -> Dict[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any, auto_save: bool = True) -> None: ...
    def save(self) -> bool: ...
    async def save_async(self) -> bool: ...

    @property
    def raw(self) -> Dict[str, Any]: ...

__all__ = [
    "IConfigRepository",
    "IStateRepository"
]
