from typing import Protocol, runtime_checkable, Optional, List, Dict, Tuple, Any
import psutil
from core.config.models import BotConfig

@runtime_checkable
class ILogRotator(Protocol):
    """Protocol for log file rotation, archiving, and size limiting."""
    max_bytes: int
    backup_count: int

    def rotate_file(self, file_path: str, force: bool = False) -> Tuple[bool, str]: ...
    async def rotate_file_async(self, file_path: str, force: bool = False) -> Tuple[bool, str]: ...
    def rotate_bot_log(self, bot_cfg: BotConfig, force: bool = False) -> Tuple[bool, str]: ...
    async def rotate_bot_log_async(self, bot_cfg: BotConfig, force: bool = False) -> Tuple[bool, str]: ...
    def rotate_all_bots(self, bots: Dict[str, BotConfig], force: bool = False) -> List[Tuple[BotConfig, bool, str]]: ...
    async def rotate_all_bots_async(self, bots: Dict[str, BotConfig], force: bool = False) -> List[Tuple[BotConfig, bool, str]]: ...

@runtime_checkable
class IProcessSpawner(Protocol):
    """Protocol for low-level process creation, termination, and systemd interactions."""
    stop_timeout: float
    restart_wait: float
    log_rotator: Optional[ILogRotator]

    def spawn(self, bot_config: BotConfig, env: dict) -> Optional[int]: ...
    async def terminate_process(self, process: psutil.Process) -> bool: ...
    def find_all_processes_in_path(self, bot_path: str) -> List[int]: ...
    async def kill_rogue_processes(self, bot_path: str) -> None: ...
    def start_service(self, service_name: str) -> bool: ...
    def stop_service(self, service_name: str) -> bool: ...
    def restart_service(self, service_name: str) -> bool: ...
    def get_systemd_state(self, service_name: str) -> str: ...
    def get_systemd_pid(self, service_name: str) -> Optional[int]: ...
    async def get_systemd_pid_async(self, service_name: str, retries: int = 3) -> Optional[int]: ...
    def execute_manager_restart(self) -> None: ...
    def execute_manager_shutdown(self) -> None: ...

@runtime_checkable
class IProcessTracker(Protocol):
    """Protocol for tracking active processes, metrics collection, and unexpected termination detection."""
    managed_processes: Dict[str, psutil.Process]
    manual_stop: set

    def is_running(self, bot_id: str) -> bool: ...
    def register(self, bot_id: str, pid: int) -> None: ...
    def unregister(self, bot_id: str) -> None: ...
    def mark_manual_stop(self, bot_id: str) -> None: ...
    def clear_manual_stop(self, bot_id: str) -> None: ...
    def discover_processes(self, bots: Dict[str, BotConfig]) -> int: ...
    def get_stats(
        self,
        bot_id: str,
        bot_cfg: Optional[BotConfig] = None,
        all_bots: Optional[Dict[str, BotConfig]] = None
    ) -> Optional[Dict[str, Any]]: ...
    def fetch_unexpected_stops(
        self,
        bots: Dict[str, BotConfig],
        spawner: Optional[IProcessSpawner] = None
    ) -> List[Tuple[str, BotConfig]]: ...

@runtime_checkable
class IGitClient(Protocol):
    """Protocol for Git repository operations and pip package management."""
    requirements_file: str
    rollback_ref: str

    def is_git_repo(self, repo_path: str) -> bool: ...
    def clean_locks(self, repo_path: str) -> None: ...
    def get_commit_details(self, repo_path: str, rev: str = "HEAD") -> Optional[Dict[str, str]]: ...
    def get_remote_url(self, repo_path: str) -> Optional[str]: ...
    def check_is_behind(self, repo_path: str, branch: str = "origin/main") -> bool: ...
    async def check_is_behind_async(self, repo_path: str, branch: str = "origin/main") -> bool: ...
    def update_repo(
        self,
        repo_path: str,
        branch: str = "origin/main"
    ) -> Tuple[bool, str, bool, Optional[Dict[str, Any]]]: ...
    async def update_repo_async(
        self,
        repo_path: str,
        branch: str = "origin/main"
    ) -> Tuple[bool, str, bool, Optional[Dict[str, Any]]]: ...
    def rollback_repo(self, repo_path: str) -> Tuple[bool, str, bool, Optional[Dict[str, Any]]]: ...
    async def rollback_repo_async(self, repo_path: str) -> Tuple[bool, str, bool, Optional[Dict[str, Any]]]: ...
    def install_dependencies(self, repo_path: str, bot_cmd: Optional[str] = None) -> Tuple[bool, str]: ...
    async def install_dependencies_async(self, repo_path: str, bot_cmd: Optional[str] = None) -> Tuple[bool, str]: ...

@runtime_checkable
class IMetricsCollector(Protocol):
    """Protocol for hardware and OS metrics collection."""
    def get_os_info(self) -> str: ...
    def calculate_network_speed(self) -> Tuple[float, float, str]: ...
    def get_system_metrics(self) -> Dict[str, Any]: ...

__all__ = [
    "ILogRotator",
    "IProcessSpawner",
    "IProcessTracker",
    "IGitClient",
    "IMetricsCollector"
]
